# Keras Functional API

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import tensorflow as tf
from tensorflow import keras

In [2]:
df = pd.read_csv("data/housing.csv")
df.dropna(inplace=True)

In [3]:
X = df.drop(['median_house_value','ocean_proximity'], axis=1)
Y = df[['median_house_value']]

In [4]:
std_scaler = MinMaxScaler()
X, Y = std_scaler.fit_transform(X), std_scaler.fit_transform(Y)
# X = std_scaler.fit_transform(X)

In [5]:
_, x_test = train_test_split(X, test_size=.2)
x_train, x_valid = train_test_split(_, test_size=.2)

_, y_test = train_test_split(Y, test_size=.2)
y_train, y_valid = train_test_split(_, test_size=.2)

In [18]:
input_ = keras.layers.Input(shape = x_train.shape[1:])
hidden1 = keras.layers.Dense(64, activation = 'relu')(input_)
hidden2 = keras.layers.Dense(64, activation = 'relu')(hidden1)
concat = keras.layers.Concatenate()([input_, hidden2])
output = keras.layers.Dense(1)(concat)
model = keras.Model(inputs=[input_], outputs=[output])

model.compile(loss="mean_absolute_error", optimizer="sgd")

model.fit(x_train, y_train, epochs=20, validation_data = (x_valid, y_valid))

Train on 13076 samples, validate on 3270 samples
Epoch 1/20
13076/13076 [==============================] - 1s 60us/sample - loss: 0.1894 - val_loss: 0.1852
Epoch 2/20
13076/13076 [==============================] - 0s 34us/sample - loss: 0.1822 - val_loss: 0.1853
Epoch 3/20
13076/13076 [==============================] - 0s 37us/sample - loss: 0.1817 - val_loss: 0.1840
Epoch 4/20
13076/13076 [==============================] - 0s 38us/sample - loss: 0.1812 - val_loss: 0.1840
Epoch 5/20
13076/13076 [==============================] - 0s 38us/sample - loss: 0.1810 - val_loss: 0.1840
Epoch 6/20
13076/13076 [==============================] - 0s 37us/sample - loss: 0.1809 - val_loss: 0.1843
Epoch 7/20
13076/13076 [==============================] - 0s 36us/sample - loss: 0.1808 - val_loss: 0.1839
Epoch 8/20
13076/13076 [==============================] - 0s 37us/sample - loss: 0.1807 - val_loss: 0.1838
Epoch 9/20
13076/13076 [==============================] - 0s 37us/sample - loss: 0.1807 - val_l

In [8]:
mse_test = model.evaluate(x_test, y_test)

4087/4087 [==============================] - 0s 24us/sample - loss: 0.1831


In [10]:
X_new = x_test[:3]
y_pred = model.predict(X_new)
y_pred

array([[0.28712523],
       [0.35207018],
       [0.34439915]], dtype=float32)

In [11]:
y_test[:3]

array([[0.25649585],
       [0.15587771],
       [0.30494926]])

In [48]:
x_test[:1]

array([[0.4312749 , 0.67693943, 0.41176471, 0.05432626, 0.07635009,
        0.02315087, 0.05410294, 0.11763286]])

In [49]:
y_test

array([[0.08928004],
       [0.41175294],
       [0.31051625],
       ...,
       [0.25525874],
       [0.58103059],
       [0.32701102]])